<a href="https://colab.research.google.com/github/yellowgram1543/6-Stages-of-AIML/blob/main/AIML0_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy — Concept (AI/ML Focus)

### What is NumPy?

* **NumPy (Numerical Python)** is the **foundation library** for scientific computing in Python.
* In AI/ML, almost all libraries (Pandas, TensorFlow, PyTorch, Scikit-learn) internally use **NumPy arrays**.

---

### Why not just Python lists?

* Python lists are **slow** for large datasets.
* NumPy arrays are:

  * **Faster** (written in C under the hood).
  * **Memory efficient** (store data in a compact form).
  * **Vectorized** (you can apply operations on entire arrays without loops).

---

### Core Idea

* A **NumPy array (ndarray)** is like a **grid of numbers**, all of the **same type** (int, float, etc.), arranged in **1D, 2D, or higher dimensions**.
* This makes them perfect for representing:

  * **Vectors** (1D array)
  * **Matrices** (2D array)
  * **Tensors** (3D+ arrays, heavily used in Deep Learning)

---

### Example in AI/ML Context

* A **dataset** can be stored as a 2D NumPy array (rows = samples, columns = features).
* An **image** is often stored as a 3D NumPy array (height × width × channels).
* Matrix operations (dot products, multiplications) are core to ML algorithms — NumPy makes them super easy.

In [6]:
# importing
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
b = arr * 2  # Multiply every element by 2 → [2 4 6 8 10]
print(arr, b)

[1 2 3 4 5] [ 2  4  6  8 10]


In [9]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [10]:
m = matrix + 10
print(matrix,"\n new array","\n" , m)

[[1 2 3]
 [4 5 6]] 
 new array 
 [[11 12 13]
 [14 15 16]]


### Core Attributes
- **Number of Dimensions**: The number of dimensions is the array's `ndim` attribute. It tells you how many indices you need to specify to access a single element. A 1-D array has ndim=1, a 2-D array has ndim=2, and so on.
- `ndarray.shape`: A tuple of integers that indicates the size of the array in each dimension. For example, a 2D array with 3 rows and 4 columns would have a shape of (3, 4).
- `ndarray.size`: The total number of elements in the array. This is the product of the elements in the shape tuple.
- `ndarray.dtype`: The data type of the elements in the array (e.g., int32, float64). All elements must have the same dtype
- `ndarray.itemsize`: The size in bytes of each element.
- `ndarray.data`: The buffer containing the actual elements of the array.

In [11]:
# array properties
print(arr.shape)
print(arr.dtype)
print(matrix.shape)  # (2, 3) → 2 rows, 3 columns
print(matrix.dtype)  # data type (int32, float64, etc.)

(5,)
int64
(2, 3)
int64


In [12]:
# array indexing and slicing
print(matrix[0, 1])   # element in first row, second column → 2
print(matrix[:, 2])   # all rows, third column → [3 6]

2
[3 6]


### Indexing in detail

In [13]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A.ndim, A.shape) #dimension and shape of the matrix

print("\n Access an element:", A[1, 2])  # Output: 6

print("\n Row selection:", A[0])  # Row Selection: To get the entire row, specify the row index.

print("\n Column Selection:", A[:, 1])  # Column Selection: Use the colon (:) to select all rows, then specify the column index.

2 (3, 3)

 Access an element: 6

 Row selection: [1 2 3]

 Column Selection: [2 5 8]




---


**Negative indices** count from the end of the array. This is very useful for selecting the last or second-to-last element without knowing the array's size.

In [14]:
a = np.array([1, 2, 3, 4, 5])
print(a[-1])  # Output: 5 (last element)
print(a[-2])  # Output: 4 (second-to-last element)

5
4




---


**Ellipsis (...)**

The ellipsis is a shorthand for selecting all remaining axes. It's especially useful for working with high-dimensional arrays, where you only want to specify a few axes and let NumPy handle the rest.

In [15]:
B = np.arange(27).reshape(3, 3, 3) # A 3x3x3 tensor
print("B: \n", B)
print("\n Ex \n", B[0, 1])
print("\n Ex2 \n", B[:, 1, :])
print("\n Ellipsis \n", B[..., 0])
# the last index fixed at 0, keep everything else.
# It is equivalent to B[:, :, 0]
# Output:
# [[ 0  3  6]
#  [ 9 12 15]
#  [18 21 24]]

B: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

 Ex 
 [3 4 5]

 Ex2 
 [[ 3  4  5]
 [12 13 14]
 [21 22 23]]

 Ellipsis 
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [16]:
C = np.arange(24).reshape(2, 3, 4)
print("\n", C)
print("\n", C.shape)     # (2, 3, 4)

#Dimension 0 → Depth (2 slices)
#Dimension 1 → Rows (3 rows per slice)
#Dimension 2 → Columns (4 columns per row)


 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 (2, 3, 4)




---


**New Axis** (`None` / `np.newaxis`)

This adds a new dimension of size 1 to an array. It's often used to make arrays compatible for broadcasting.

`np.newaxis` is a convenient alias for `None` in NumPy. When used in array indexing, it adds a new axis (dimension) of size 1 to the array.

In [17]:
print(np.newaxis is None)  # True

True


**Example 1: Turn a 1D array into a 2D row vector**

In [18]:
a = np.array([1, 2, 3])
print("Original shape:", a.shape)  # (3,)

# Add new axis at the beginning → becomes row vector (1, 3)
b = a[np.newaxis, :]
print("New shape:", b.shape)       # (1, 3)
print(b)
# Output: [[1 2 3]]

Original shape: (3,)
New shape: (1, 3)
[[1 2 3]]


**Example 2: Turn a 1D array into a 2D column vector**

In [19]:
x = np.array([1, 2, 3])
print(f"Original shape: {x.shape}") # (3,)
x_reshaped = x[:, np.newaxis]
print(f"Reshaped array:\n{x_reshaped}")
print(f"New shape: {x_reshaped.shape}") # (3, 1)

Original shape: (3,)
Reshaped array:
[[1]
 [2]
 [3]]
New shape: (3, 1)


**Example 3: Add Multiple New Axes**

In [20]:
a = np.array([1, 2, 3])

# Make it shape (1, 3, 1)
b = a[np.newaxis, :, np.newaxis]
print(b.shape)   # (1, 3, 1)
print(b)

(1, 3, 1)
[[[1]
  [2]
  [3]]]




---


**Fancy Indexing**

Fancy indexing means using arrays of integers (or boolean masks — though boolean is technically a separate category) to access elements in a NumPy array. Unlike basic slicing (:), fancy indexing allows you to pick arbitrary elements in any order, even repeating them.

Fancy indexing always returns a copy of the data (not a view), unlike basic slicing which returns a view.

In [21]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 0])

result = arr[indices]
print(result)  # [20 40 10]

[20 40 10]


**1D Fancy Indexing**

In [22]:
arr = np.array([100, 200, 300, 400, 500])

# Select specific indices
print(arr[[0, 2, 4]])    # [100 300 500]

# Repeating indices is allowed
print(arr[[0, 0, 1, 1]]) # [100 100 200 200]

# Negative indices work too
print(arr[[-1, -2]])     # [500 400]

# You can use a NumPy array or a Python list — both work
idx = np.array([3, 1])
print(arr[idx])          # [400 200]

[100 300 500]
[100 100 200 200]
[500 400]
[400 200]


**2D Fancy Indexing**

In [23]:
A = np.array([[ 1,  2,  3],
              [ 4,  5,  6],
              [ 7,  8,  9],
              [10, 11, 12]])

rows = np.array([0, 2, 1])
cols = np.array([1, 2, 0])

print(A[rows, cols])

[2 9 4]


**Fancy Indexing + Slicing**

In [24]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

rows = [0, 2]
print(A[rows, :])  # Select entire rows 0 and 2
# Output:
# [[ 1  2  3  4]
#  [ 9 10 11 12]]

cols = [1, 3]
print(A[:, cols])  # Select columns 1 and 3 from all rows
# Output:
# [[ 2  4]
#  [ 6  8]
#  [10 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]]


**Modifying Arrays with Fancy Indexing**

In [25]:
arr = np.array([10, 20, 30, 40, 50])
arr[[1, 3]] = 999
print(arr)  # [ 10 999  30 999  50]

# You can assign different values too
arr[[0, 2, 4]] = [1, 2, 3]
print(arr)

[ 10 999  30 999  50]
[  1 999   2 999   3]


In [26]:
A = np.zeros((3,3))
print(A, "\n")
rows = [0, 1, 2]
cols = [0, 1, 2]
A[rows, cols] = [1, 2, 3]  # Set diagonal
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


**Shuffling or Reordering Data**

In [27]:
data = np.array([100, 200, 300, 400])
order = [3, 0, 2, 1]
shuffled = data[order]
print(shuffled)  # [400 100 300 200]

[400 100 300 200]


**Fancy indexing returns a COPY**

In [28]:
arr = np.array([1, 2, 3, 4])
subset = arr[[0, 2]]   # subset is a COPY
subset[0] = 999
print(arr)             # unchanged → [1 2 3 4]

[1 2 3 4]




---

**Boolean (Mask) Indexing**

This is a powerful technique for filtering arrays based on a condition. You create a boolean array (or "mask") and use it to select elements from the original array where the mask is `True`.

In [29]:
arr = np.array([10, 20, 30, 40, 50])
mask = np.array([True, False, True, False, True])

result = arr[mask]
print(result)  # [10 30 50]

[10 30 50]


In [30]:
arr = np.array([1, 5, 3, 9, 2, 8])

# Create mask: elements greater than 4
mask = arr > 4
print(mask)  # [False  True False  True False  True]

# Use mask to select those elements
selected = arr[mask]
print(selected)  # [5 9 8]

[False  True False  True False  True]
[5 9 8]


Use parentheses around conditions!

`arr > 3 & arr < 8` → ❌ Wrong (operator precedence)

`(arr > 3) & (arr < 8)` → ✅ Correct

In [31]:
# Select elements between 3 and 8 (inclusive)
mask = (arr >= 3) & (arr <= 8)
print(arr[mask])  # [5 3 8]

# NOT less than 5
mask = ~(arr < 5)
print(arr[mask])  # [5 9 8]

[5 3 8]
[5 9 8]


In [32]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

mask = A > 5
print(mask, "\n")
print(A[mask])

[[False False False]
 [False False  True]
 [ True  True  True]] 

[6 7 8 9]


**Shape Behavior**

- Boolean indexing flattens the result to 1D by default (it selects elements matching True, regardless of original shape).
- To preserve structure, combine with slicing or use `np.where` or advanced techniques.

In [33]:
arr = np.array([1, 5, 3, 9, 2])
mask = arr > 4
indices = np.where(mask)  # Returns tuple of arrays (for each axis)

print(indices)     # (array([1, 3]),)
print(arr[indices]) # [5 9] — same as arr[mask]

result = np.where(arr > 4, 't', 'f')
print(result)

(array([1, 3]),)
[5 9]
['f' 't' 'f' 't' 'f']


You can also assign values using boolean masks — extremely useful for cleaning or transforming data.

In [34]:
arr = np.array([1, -2, 3, -4, 5])

# Replace negative values with 0
arr[arr < 0] = 0
print(arr)

# Double values greater than 2
arr[arr > 2] *= 2
print(arr)

[1 0 3 0 5]
[ 1  0  6  0 10]


**Combining Boolean Indexing with Fancy or Slicing**

In [35]:
A = np.array([[1, 2, 3],   # sum=6 → True
              [0, 1, 1],   # sum=2 → False
              [2, 2, 3]])  # sum=7 → True

row_mask = A.sum(axis=1) > 5
col_mask = A.sum(axis=0) > 5

print(row_mask)
print(col_mask, "\n")

selected_cols = A[:, col_mask]
print(selected_cols, "\n")

selected_rows = A[row_mask]   # Select entire rows where condition holds
print(selected_rows)

[ True False  True]
[False False  True] 

[[3]
 [1]
 [3]] 

[[1 2 3]
 [2 2 3]]


`axis=0`: This refers to the rows. When you perform an operation along axis=0, you are applying the operation down the columns.

`axis=1`: This refers to the columns. When you perform an operation along axis=1, you are applying the operation across the rows.

**Real-World Use Cases**
1. Data Cleaning — Replace Outliers or Invalid Values
2. Filtering Datasets
3. Image Processing — Thresholding
4. Machine Learning — Select Samples by Label or Score

> Boolean indexing returns a COPY

In [36]:
arr = np.array([1, 2, 3, 4])
subset = arr[arr > 2]  # COPY
subset[0] = 999
print(arr)

[1 2 3 4]




> Mask must be same shape (or broadcastable) as array being indexed



In [40]:
arr = np.array([1, 2, 3, 4])
# mask = np.array([True, False])  # ❌ ValueError — shape mismatch

mask = np.array([True, False, True, False])
print(arr[mask])

[1 3]




> Use .any() or .all() with masks for logic



In [41]:
A = np.array([[1, 2],
              [3, 4]])

# Are any elements > 3?
print((A > 3).any())   # True

# Are all elements > 0?
print((A > 0).all())   # True

True
True


### Slicing in detail

**Basic Slice Syntax**

Slicing is a powerful way to select a subset of an array. The basic syntax a`[start:stop:step] `allows you to extract elements without changing the original array's structure or data type.

`start`: The index where the slice begins (inclusive). If omitted, it defaults to the beginning of the axis (index 0).

`stop`: The index where the slice ends (exclusive). The element at this index is not included. If omitted, it defaults to the end of the axis.

`step`: The interval between elements. A positive step moves forward, and a negative step moves backward. The default step is 1.

In [42]:
import numpy as np
arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
# Select elements from index 2 up to (but not including) index 6
print(arr[2:6]) # Output: [20 30 40 50]

[20 30 40 50]




---


**Multi-Axis Slicing**

For multi-dimensional arrays, you can apply slicing to each axis by separating the slice specifications with a comma.



```
 Syntax: arr[axis0_slice, axis1_slice, axis2_slice, ...]
```



In [43]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])

print(A.shape)  # (4, 4) → 4 rows, 4 columns

(4, 4)


In [44]:
B = A[1:3, 0:2]  # Rows 1-2 (inclusive start, exclusive stop), columns 0-1
print(B)

[[ 5  6]
 [ 9 10]]


First index → axis 0 (rows)

Second index → axis 1 (columns)

In [46]:
# Create a 3x3x3 array
C = np.arange(27).reshape(3, 3, 3)
print(C, "\n")
print(C.shape)

# Visualize as 3 layers of 3x3 matrices:
# Layer 0: C[0, :, :]
# Layer 1: C[1, :, :]
# Layer 2: C[2, :, :]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

(3, 3, 3)


In [47]:
D = C[1, 0:2, 1:3]
print(D)

[[10 11]
 [13 14]]


1 → selects layer 1 (axis 0)

0:2 → selects first 2 rows (axis 1)

1:3 → selects columns 1 and 2 (axis 2)

In [49]:
print(A[:, 1], "\n")     # All rows, column 1 → shape (4,)
print(A[2, :], "\n")     # Row 2, all columns → shape (4,)
print(A[:, :])   # Everything → same as A

[ 2  6 10 14] 

[ 9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]




---


**Step Slicing Across Axes**

In [50]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])

# Every other row, every other column
E = A[::2, ::2]
print(E)

[[ 1  3]
 [ 9 11]]


In [51]:
F = A[::-1, :]    # Reverse rows
print(F, "\n")

G = A[:, ::-1]    # Reverse columns
print(G)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]] 

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
# Slice + Integer Index
A[1:3, 2]  # Rows 1-2, column 2 → shape (2,)

# Slice + Boolean Mask
mask = np.array([True, False, True, False])
A[mask, 1:3]  # Rows where mask is True, columns 1-2
# Row 0: [2, 3]
# Row 2: [10, 11]

**Slices are Views**: When you create a slice using basic slicing, NumPy does not create a new array in memory. Instead, it creates a "view" that points to a specific part of the original array's data buffer. This is incredibly memory-efficient, especially for large datasets. Any modification to the view will directly affect the original array.

In [52]:
original_array = np.array([10, 20, 30, 40, 50])
# Create a view of the original array
my_view = original_array[1:4]
print(f"Before modification: {original_array}")

# Modify an element in the view
my_view[0] = 99

print(f"After modification: {original_array}")

Before modification: [10 20 30 40 50]
After modification: [10 99 30 40 50]


**Fancy Indexing Returns a Copy**: In contrast, when you use fancy indexing (using a list or array of integers as indices), NumPy returns a copy of the selected data. The new array occupies its own memory space, so changes to the copy will not affect the original array.

In [53]:
original_array = np.array([10, 20, 30, 40, 50])
# Create a copy using fancy indexing
my_copy = original_array[[1, 2, 3]]

# Modify an element in the copy
my_copy[0] = 99

print(f"After modification: {original_array}")

After modification: [10 20 30 40 50]


### Vectorized operations

Vectorized operations are operations that are applied element-wise to entire arrays (vectors, matrices, tensors) without explicit Python loops.

**Non-Vectorized (Slow — Python loop)**

In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
result = np.empty(4)

In [56]:
# NON-VECTORIZED
for i in range(len(a)):
    result[i] = a[i] + b[i]

print(result)  # [6. 8. 10. 12.]

[ 6.  8. 10. 12.]


In [57]:
# VECTORIZED
result = a + b
print(result)  # [6 8 10 12]

[ 6  8 10 12]


**Operations Are Vectorized in NumPy**

In [ ]:
# Arithmetic

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b   # [5 7 9]
a * b   # [4 10 18]
a ** 2  # [1 4 9]
a / b   # [0.25 0.4 0.5]

In [61]:
# Mathematical Functions

np.sin(a)      # [sin(1), sin(2), sin(3)]
np.exp(a)      # [e^1, e^2, e^3]
np.log(a)      # [ln(1), ln(2), ln(3)]
np.sqrt(a)     # [1, √2, √3]

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [60]:
# Comparison Operations

a > 2          # [False False True]
a == b         # [False False False]

array([False, False, False, False])

In [59]:
# Aggregations (Reduce along axes)

np.sum(a)      # 6
np.mean(a)     # 2.0
np.max(a)      # 3
np.std(a)      # standard deviation

np.float64(1.118033988749895)

In [58]:
result = np.where(a > 0, np.sqrt(a), 0)
# OR
result = np.sqrt(a) * (a > 0)  # since False=0, True=1

**Advanced Vectorization Techniques**
1. np.where — Vectorized Conditional
2. np.select — Multiple Conditions
3. np.clip — Bound Values


In [79]:
a = np.array([-1, 2, -3, 4])
# np.where applies the conditional logic element-wise across the array.
# This is a form of vectorization, avoiding explicit Python loops.
result = np.where(a > 2, a, -a)  # absolute value
print(result, "\n")  # [1 2 3 4]
result1 = np.where(a > 2, -a, a)
print(result1)

[ 1 -2  3  4] 

[-1  2 -3 -4]


In [76]:
x = np.arange(10)
conditions = [x < 3, x > 7, (x >= 3) & (x <= 7)]
choices = [1, 100, x**2]
result = np.select(conditions, choices, default=np.nan)
print(result)
# [  0   0   0   9  16  25  36  49 100 100]

[  1.   1.   1.   9.  16.  25.  36.  49. 100. 100.]


In [77]:
a = np.array([-5, 1, 10, 3])
clipped = np.clip(a, 0, 5)  # [0 1 5 3]
print(clipped)

[0 1 5 3]


In [ ]:
x = np.arange(1,5)          # Create a 1D NumPy array with elements from 1 up to (but not including) 5.
print("x:", x)

y = x * 2                   # Perform element-wise multiplication: each element in x is multiplied by 2.
print("y:", y)

z = np.sin(x)               # Apply the sine function element-wise to each element in x (a universal function or ufunc).
print("z:", z)

S = np.arange(12).reshape(3,4) # Create a 1D array from 0 to 11 and reshape it into a 2D array (3 rows, 4 columns).
print("S:\n", S)

col_sum = S.sum(axis=0)     # Calculate the sum of elements along axis 0 (down the columns).
print("col_sum:", col_sum)

dot = x.dot(x)              # Calculate the dot product of vector x with itself.
print("dot:", dot)

x += 1                      # Perform in-place element-wise addition: add 1 to each element of x and update x directly.
print("x after += 1:", x)

mask = S % 2 == 0           # Create a boolean mask: True where elements in S are even, False otherwise.
print("mask:\n", mask)

S[mask] = -1                # Use the boolean mask to set all even elements in S to -1.
print("S after masking:\n", S)

### Reshaping

`a.reshape(new_shape)` returns a new array with the specified shape. Importantly, it attempts to return a view of the original array whenever possible. This means the new array shares memory with the original. If modifications are made to the new array, they will also be reflected in the original. If the new shape requires a different memory layout, `reshape()` will return a copy.

In [81]:
a = np.arange(6)  # Creates array [0 1 2 3 4 5] with shape (6,)
b = a.reshape(2, 3) # Reshapes into a 2x3 matrix
print(f"Original array 'a':\n{a}")
print(f"Reshaped array 'b':\n{b}")

# Both 'a' and 'b' share the same data.
print(f"Are 'a' and 'b' sharing memory? {np.may_share_memory(a, b)}") # Output: True

# Modifying 'b' also modifies 'a'
b[0, 0] = 99
print(f"Array 'a' after modifying 'b':\n{a}") # Output: [99  1  2  3  4  5]

Original array 'a':
[0 1 2 3 4 5]
Reshaped array 'b':
[[0 1 2]
 [3 4 5]]
Are 'a' and 'b' sharing memory? True
Array 'a' after modifying 'b':
[99  1  2  3  4  5]


**The -1 Trick**

NumPy can automatically calculate one of the dimensions for you. By passing `-1` as a dimension in the` reshape()` method, you are telling NumPy to figure out what that dimension's size should be based on the other dimensions and the total number of elements. This is a very common and convenient shortcut.

In [87]:
a = np.arange(12)  # Shape (12,)
b = a.reshape(3, -1)   # The new shape is (3, 4) because 3 * 4 = 12
print(f"Reshaped with (3, -1):\n{b}")

c = a.reshape(-1, 6)
print("\n" ,c)

Reshaped with (3, -1):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


**Flattening vs. Raveling**

Both `flatten()` and `ravel()` are methods for converting a multi-dimensional array into a 1D array. However, they differ in how they handle memory.

`a.flatten()`: This method always returns a copy of the array. The new 1D array is independent of the original. This is safer if you want to avoid modifying the original array but is less memory-efficient.

`a.ravel()`: This method always returns a view of the original array whenever possible. It's generally faster and more memory-efficient as it doesn't create a new data buffer. Changes made to the raveled array will be reflected in the original.

In [88]:
A = np.array([[1, 2], [3, 4]])

# Using ravel (returns a view)
raveled_view = A.ravel()
raveled_view[0] = 99
print(f"Array after raveling and modifying:\n{A}") # Output: [[99  2] [ 3  4]]

# Using flatten (returns a copy)
flattened_copy = A.flatten()
flattened_copy[0] = 1
print(f"Original array after flattening and modifying:\n{A}") # Output: [[99  2] [ 3  4]]

Array after raveling and modifying:
[[99  2]
 [ 3  4]]
Original array after flattening and modifying:
[[99  2]
 [ 3  4]]


**Resize vs. Reshape**

While they might sound similar, resize() and reshape() are fundamentally different in their purpose and behavior.

`reshape()`: Creates a new array (view or copy) with a new shape. The total number of elements must be the same.

`resize()`: Modifies the array in-place. It can increase or decrease the total number of elements. If the new shape is larger, the array is padded with zeros. If it's smaller, the array is truncated. This method changes the array object itself.

In [89]:
a = np.array([1, 2, 3])
# resize() modifies 'a' in place
a.resize((2, 4))
print(f"Resized array 'a':\n{a}")

Resized array 'a':
[[1 2 3 0]
 [0 0 0 0]]


**Removing Dimensions `(squeeze())`**: The `squeeze()` method removes axes of length 1.

In [ ]:
y = np.arange(10).reshape(1, 10, 1) # Shape is (1, 10, 1)
squeezed_y = y.squeeze() # Removes the dimensions of size 1
print(f"Squeezed shape: {squeezed_y.shape}") # Output: (10,)

- **Mismatch in Elements**: reshape() will raise a ValueError if the new shape is not compatible with the total number of elements in the original array.

- **Views vs. Copies**: This is the most common source of bugs for new NumPy users. Always be aware if an operation returns a view or a copy, as modifying one can unexpectedly change the other.

- **Checking for Views**: To programmatically check if an array is a view of another, you can check its .base attribute. If .base is None, the array is a standalone object (a copy). If it's not None, it's a view.

In [ ]:
a = np.arange(10)
b = a[0:5] # b is a view
print(b.base is a) # Output: True

c = a.copy() # c is a copy
print(c.base is None) # Output: True